<?php

/*
 {
    "COMPOSER_NO_INTERACTION": "1",
    "HEROKU_APP_DIR": "/app",
    "HEROKU_PHP_HTTPD_CONFIG_INCLUDE": "/app/vendor/heroku/heroku-buildpack-php/conf/apache2/default_include.conf",
    "DOCUMENT_ROOT": "/app/public",
    "PWD": "/app",
    "PORT": "4535",
    "COMPOSER_VENDOR_DIR": "vendor",
    "HOME": "/app",
    "HEROKU_PHP_GRACEFUL_SIGTERM": "1",
    "COMPOSER_PROCESS_TIMEOUT": "0",
    "COMPOSER_MIRROR_PATH_REPOS": "1",
    "SHLVL": "0",
    "COMPOSER_BIN_DIR": "vendor/bin",
    "WEB_CONCURRENCY": "4",
    "COMPOSER_MEMORY_LIMIT": "536870912",
    "PATH": "/app/.heroku/php/sbin:/app/.heroku/php/bin:/app/.heroku/php/bin:/app/.heroku/php/sbin:/app/.heroku/php/bin:/app/.heroku/php/sbin:/usr/local/bin:/usr/bin:/bin:/app/vendor/bin",
    "DYNO": "web.1",
    "_": "/app/.heroku/php/sbin/php-fpm",
    "USER": "u4430",
    "SCRIPT_NAME": "/index.php",
    "REQUEST_URI": "/php-nocode/gitlab/trigger/pipeline?_bypass_landing_page=yes&base_id=appDr6Oa6ehTdcbjp&project_id=35377076",
    "QUERY_STRING": "_bypass_landing_page=yes&base_id=appDr6Oa6ehTdcbjp&project_id=35377076",
    "REQUEST_METHOD": "POST",
    "SERVER_PROTOCOL": "HTTP/1.1",
    "GATEWAY_INTERFACE": "CGI/1.1",
    "REDIRECT_QUERY_STRING": "_bypass_landing_page=yes&base_id=appDr6Oa6ehTdcbjp&project_id=35377076",
    "REDIRECT_URL": "/php-nocode/gitlab/trigger/pipeline",
    "REMOTE_PORT": "15996",
    "SCRIPT_FILENAME": "/app/public/index.php",
    "SERVER_ADMIN": "you@example.com",
    "CONTEXT_DOCUMENT_ROOT": "/app/public",
    "CONTEXT_PREFIX": "",
    "REQUEST_SCHEME": "http",
    "REMOTE_ADDR": "10.1.8.99",
    "SERVER_PORT": "80",
    "SERVER_ADDR": "172.16.22.118",
    "SERVER_NAME": "javanile-webrequest.herokuapp.com",
    "SERVER_SOFTWARE": "Apache",
    "SERVER_SIGNATURE": "",
    "CONTENT_LENGTH": "2248",
    "HTTP_TOTAL_ROUTE_TIME": "0",
    "HTTP_X_REQUEST_START": "1650105419469",
    "HTTP_CONNECT_TIME": "0",
    "HTTP_VIA": "1.1 vegur",
    "HTTP_X_REQUEST_ID": "1ccc61fe-a5dc-44c0-b760-5d604696cec0",
    "HTTP_ACCEPT_ENCODING": "gzip",
    "HTTP_X_REAL_IP": "34.74.226.15:29368",
    "HTTP_X_GITLAB_TOKEN": "d97727ede181fd435e2041e415ca9e+keyTuCpAPSljkbIzS",
    "HTTP_X_GITLAB_EVENT_UUID": "096b3ce3-77b5-4084-add8-dfa39ad96a06",
    "HTTP_X_GITLAB_EVENT": "Issue Hook",
    "HTTP_X_FORWARDED_PROTO": "https",
    "HTTP_X_FORWARDED_PORT": "443",
    "HTTP_X_FORWARDED_HOST": "webrequest.cc",
    "HTTP_X_FORWARDED_FOR": "34.74.226.15:29368, 74.208.245.19",
    "CONTENT_TYPE": "application/json",
    "HTTP_USER_AGENT": "GitLab/14.10.0-pre",
    "HTTP_CONNECTION": "close",
    "HTTP_HOST": "javanile-webrequest.herokuapp.com",
    "REDIRECT_STATUS": "200",
    "FCGI_ROLE": "RESPONDER",
    "PHP_SELF": "/index.php",
    "REQUEST_TIME_FLOAT": 1650105419.476204,
    "REQUEST_TIME": 1650105419
}
 */
